language: generic
sudo: required
services: docker

env:
  - GRADLE_VERSION=2.8
  - GRADLE_VERSION=2.9
  - GRADLE_VERSION=2.10
  - GRADLE_VERSION=2.11
  - GRADLE_VERSION=2.12

before_install:
  - docker pull metahelicase/gradle:$GRADLE_VERSION

script:
  - docker run --rm -v `pwd`:/project metahelicase/gradle:$GRADLE_VERSION check --stacktrace
