language: generic
sudo: required
services: docker

before_install:
  - docker pull metahelicase/gradle:2.9
  - docker pull metahelicase/gradle:2.10

script:
  - docker run --rm -v `pwd`:/project metahelicase/gradle:2.9 check --stacktrace
  - docker run --rm -v `pwd`:/project metahelicase/gradle:2.10 check --stacktrace
