language: generic
sudo: required
services: docker

env:
  - GRADLE_VERSION=2.10
  - GRADLE_VERSION=2.11
  - GRADLE_VERSION=2.12
  - GRADLE_VERSION=2.13
  - GRADLE_VERSION=2.14
  - GRADLE_VERSION=2.14.1

before_install:
  - docker pull metahelicase/gradle:$GRADLE_VERSION

script:
  - docker run --rm -v `pwd`:/project metahelicase/gradle:$GRADLE_VERSION check --stacktrace
